#custom
custom:
  mysql:
    address: localhost
    password: fkz
    port: 3306
    username: fkz
    database: fkz
    config: autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useAffectedRows=true

#用于显示绑定的参数具体值

logging:
  level:
    org:
      hibernate:
        #        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace